import { auth, db } from "../pages/firebase-db.js";
import { requireActiveAdmin } from "../pages/admin-authorization.js";
import { getFunctions, httpsCallable } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-functions.js";
import { getStorage, ref, uploadBytes, getDownloadURL } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-storage.js";

const functions = getFunctions(undefined, "asia-northeast1"), storage = getStorage();
const manageCompany = httpsCallable(functions,"manageAdminWorkCompany"), manageJob = httpsCallable(functions,"manageAdminWorkJob"), getData = httpsCallable(functions,"getAdminWorkData");
let companies=[], jobs=[];
const $=id=>document.getElementById(id), esc=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const companyFields=["Name","Description","Address","Phone","Email","WebsiteUrl","LineUrl","InstagramUrl","XUrl","TiktokUrl"];
const jobFields=["Title","Industry","Occupation","EmploymentType","Salary","Location","Station","WorkHours","Holidays","Description","Requirements","Benefits","AgeRequirement","ApplyType","ApplyValue","LineUrl","InstagramUrl","XUrl","TiktokUrl","WebsiteUrl","Status","PublishStartDate","PublishEndDate","DisplayOrder","AdminMemo"];
async function upload(file,path){if(!file)return null;if(file.size>5*1024*1024)throw Error("画像は5MB以下にしてください。");const target=ref(storage,path);await uploadBytes(target,file,{contentType:file.type});return{url:await getDownloadURL(target),path};}
function id(){return crypto.randomUUID().replaceAll("-","").slice(0,20)}
async function load(){const result=(await getData({})).data;companies=result.companies||[];jobs=result.jobs||[];render();}
function render(){
  $("jobCompanyId").innerHTML='<option value="">選択してください</option>'+companies.map(c=>`<option value="${esc(c.companyId)}">${esc(c.name)}</option>`).join("");
  $("companyList").innerHTML=companies.map(c=>`<div class="item"><b>${esc(c.name)}</b><div class="actions"><button type="button" data-company-edit="${esc(c.companyId)}">編集</button><button type="button" class="danger" data-company-delete="${esc(c.companyId)}">削除</button></div></div>`).join("")||"企業情報はありません。";
  $("jobList").innerHTML=jobs.map(j=>`<div class="item"><b>${esc(j.title)}</b> — ${esc(j.companyName)} <span class="badge">${esc(j.status)}</span><div>${esc(j.occupation)} / ${esc(j.location)} / ${esc(j.salary)}</div><div class="actions"><button type="button" data-job-edit="${esc(j.jobId)}">編集</button><button type="button" data-job-status="published" data-id="${esc(j.jobId)}">公開</button><button type="button" data-job-status="paused" data-id="${esc(j.jobId)}">停止</button><button type="button" class="danger" data-job-delete="${esc(j.jobId)}">削除</button></div></div>`).join("")||"求人はありません。";
}
function clearCompany(){$("companyForm").reset();$("companyId").value=""}function clearJob(){$("jobForm").reset();$("jobId").value="";$("jobDisplayOrder").value="999"}
function editCompany(companyId){const c=companies.find(x=>x.companyId===companyId);if(!c)return;$("companyId").value=c.companyId;companyFields.forEach(k=>$("company"+k).value=c[k[0].toLowerCase()+k.slice(1)]||"");scrollTo({top:0,behavior:"smooth"})}
function editJob(jobId){const j=jobs.find(x=>x.jobId===jobId);if(!j)return;$("jobId").value=j.jobId;$("jobCompanyId").value=j.companyId;jobFields.forEach(k=>$("job"+k).value=j[k[0].toLowerCase()+k.slice(1)]??"");$("jobBeginnerWelcome").value=String(j.beginnerWelcome===true);$("jobForm").scrollIntoView({behavior:"smooth"})}
$("companyForm").addEventListener("submit",async e=>{e.preventDefault();const status=$("companyStatus");status.textContent="保存中...";try{const companyId=$("companyId").value||id(),old=companies.find(c=>c.companyId===companyId)||{};const logo=await upload($("companyLogoFile").files[0],`work-companies/${companyId}/logo-${id()}`),main=await upload($("companyMainFile").files[0],`work-companies/${companyId}/main-${id()}`);const company={companyId};companyFields.forEach(k=>company[k[0].toLowerCase()+k.slice(1)]=$("company"+k).value.trim());Object.assign(company,{logoUrl:logo?.url||old.logoUrl||"",logoStoragePath:logo?.path||old.logoStoragePath||"",mainImageUrl:main?.url||old.mainImageUrl||"",mainImageStoragePath:main?.path||old.mainImageStoragePath||""});await manageCompany({action:"save",company});status.textContent="保存しました。";clearCompany();await load()}catch(error){status.textContent=error.message}});
$("jobForm").addEventListener("submit",async e=>{e.preventDefault();const status=$("jobStatusMessage");status.textContent="保存中...";try{const jobId=$("jobId").value||id(),old=jobs.find(j=>j.jobId===jobId)||{},company=companies.find(c=>c.companyId===$("jobCompanyId").value);if(!company)throw Error("企業を選択してください。");const main=await upload($("jobMainFile").files[0],`work-images/${jobId}/main-${id()}`),logo=await upload($("jobLogoFile").files[0],`work-images/${jobId}/logo-${id()}`);const files=[...$("jobImageFiles").files];if(files.length>10)throw Error("詳細画像は10枚以内です。");const uploaded=[];for(const file of files)uploaded.push(await upload(file,`work-images/${jobId}/detail-${id()}`));const job={jobId,companyId:company.companyId,companyName:company.name};jobFields.forEach(k=>job[k[0].toLowerCase()+k.slice(1)]=$("job"+k).value.trim());job.displayOrder=Number($("jobDisplayOrder").value);job.beginnerWelcome=$("jobBeginnerWelcome").value==="true";Object.assign(job,{mainImageUrl:main?.url||old.mainImageUrl||"",mainImageStoragePath:main?.path||old.mainImageStoragePath||"",logoUrl:logo?.url||old.logoUrl||company.logoUrl||"",logoStoragePath:logo?.path||old.logoStoragePath||"",imageUrls:uploaded.length?uploaded.map(x=>x.url):(old.imageUrls||[]),imageStoragePaths:uploaded.length?uploaded.map(x=>x.path):(old.imageStoragePaths||[])});await manageJob({action:"save",job});status.textContent="保存しました。";clearJob();await load()}catch(error){status.textContent=error.message}});
document.addEventListener("click",async e=>{const b=e.target.closest("button");if(!b)return;if(b.dataset.companyEdit)editCompany(b.dataset.companyEdit);if(b.dataset.jobEdit)editJob(b.dataset.jobEdit);if(b.dataset.jobStatus){b.disabled=true;await manageJob({action:"status",jobId:b.dataset.id,status:b.dataset.jobStatus});await load()}if(b.dataset.jobDelete&&confirm("求人を削除しますか？画像は削除されません。")){await manageJob({action:"delete",jobId:b.dataset.jobDelete});await load()}if(b.dataset.companyDelete&&confirm("企業情報を削除しますか？")){await manageCompany({action:"delete",companyId:b.dataset.companyDelete});await load()}});
$("clearCompany").onclick=clearCompany;$("clearJob").onclick=clearJob;
const user=await requireActiveAdmin({auth,db,loginUrl:"../pages/login.html?reason=admin-required"});if(user)await load();
