import {db} from './firebase-db.js';
import {collection,getDocs,getDoc,doc,query,where,addDoc,serverTimestamp} from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';
const fallback={id:'rei',name:'れい',tagline:'美容・ファッションを中心に、ブランドの魅力を丁寧に発信します。',profile:'NOX公式アンバサダーとして活動中。',genres:['美容','ファッション','商品PR'],services:['Instagram投稿','ストーリー投稿','撮影モデル'],area:'日本国内',visible:true,priceVisible:false,images:[],sns:{}};
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const arr=v=>Array.isArray(v)?v:[];
const unique=v=>[...new Set(arr(v).map(x=>String(x).trim()).filter(Boolean))];
if(document.querySelector('#ambassadorList')){const link=document.createElement('link');link.rel='stylesheet';link.href='ambassador-list.css';document.head.appendChild(link)}
async function loadPublic(){const snap=await getDocs(query(collection(db,'ambassadors'),where('visible','==',true)));const rows=snap.docs.map(x=>({id:x.id,...x.data()}));return rows.length?rows.sort((a,b)=>(a.displayOrder??999)-(b.displayOrder??999)):[fallback]}
function photo(url,name,idx=0){return url?`<img class="amb-photo" src="${esc(url)}" alt="${esc(name)}" data-photo-index="${idx}">`:`<div class="amb-photo amb-placeholder" aria-label="${esc(name)}">NOX</div>`}
function tags(items){return `<div class="amb-tags">${arr(items).map(x=>`<span class="amb-tag">${esc(x)}</span>`).join('')}</div>`}
async function listPage(){const root=document.querySelector('#ambassadorList');if(!root)return;try{const rows=await loadPublic();root.innerHTML=rows.map(a=>{const genres=unique(a.genres),services=unique(a.services).filter(x=>!genres.includes(x));const badges=[a.featured?'<span class="amb-badge amb-badge-recommended">RECOMMENDED</span>':'',a.isNew?'<span class="amb-badge amb-badge-new">NEW</span>':''].join('');return `<article class="amb-card"><div class="amb-photo-wrap">${photo(a.mainImageUrl,a.name)}${badges?`<div class="amb-badges">${badges}</div>`:''}</div><div class="amb-card-body"><h2>${esc(a.name)}</h2><p>${esc(a.tagline||a.introduction||'')}</p>${genres.length?`<div class="amb-card-group"><h3>得意ジャンル</h3>${tags(genres)}</div>`:''}${services.length?`<div class="amb-card-group"><h3>対応可能PR</h3>${tags(services)}</div>`:''}<a class="amb-btn gold" href="ambassador-detail.html?id=${encodeURIComponent(a.id)}">詳しく見る</a></div></article>`}).join('')}catch(e){root.innerHTML='<p class="amb-empty">現在情報を読み込めません。時間をおいてお試しください。</p>'}}
function setupViewer(urls){const modal=document.querySelector('#photoModal');if(!modal||!urls.length)return;let n=0;const img=modal.querySelector('img');const show=i=>{n=(i+urls.length)%urls.length;img.src=urls[n];modal.classList.add('open');document.body.style.overflow='hidden'};document.querySelectorAll('[data-photo-index]').forEach(el=>el.addEventListener('click',()=>show(Number(el.dataset.photoIndex))));modal.querySelector('.amb-modal-close').onclick=()=>{modal.classList.remove('open');document.body.style.overflow=''};modal.querySelector('.amb-modal-prev').onclick=()=>show(n-1);modal.querySelector('.amb-modal-next').onclick=()=>show(n+1);modal.onclick=e=>{if(e.target===modal)modal.querySelector('.amb-modal-close').click()};let x=0;modal.addEventListener('touchstart',e=>x=e.touches[0].clientX,{passive:true});modal.addEventListener('touchend',e=>{const d=e.changedTouches[0].clientX-x;if(Math.abs(d)>45)show(n+(d<0?1:-1))});document.addEventListener('keydown',e=>{if(!modal.classList.contains('open'))return;if(e.key==='Escape')modal.querySelector('.amb-modal-close').click();if(e.key==='ArrowLeft')show(n-1);if(e.key==='ArrowRight')show(n+1)})}
async function detailPage(){const root=document.querySelector('#ambassadorDetail');if(!root)return;const id=new URLSearchParams(location.search).get('id')||'rei';let a=fallback;try{const s=await getDoc(doc(db,'ambassadors',id));if(s.exists()&&s.data().visible===true)a={id:s.id,...s.data()};else if(id!=='rei')throw Error()}catch(e){if(id!=='rei'){root.innerHTML='<p class="amb-empty">アンバサダーが見つかりません。</p>';return}}const urls=[a.mainImageUrl,...arr(a.galleryImageUrls)].filter(Boolean);const social=Object.entries(a.sns||{}).filter(([,v])=>v).map(([k,v])=>`<a class="amb-tag" href="${esc(v)}" target="_blank" rel="noopener noreferrer">${esc(k)}</a>`).join('');root.innerHTML=`<div class="amb-gallery">${urls.length?urls.map((u,i)=>photo(u,a.name,i)).join(''):photo('',a.name)}</div><article class="amb-panel"><p class="amb-kicker">NOX OFFICIAL AMBASSADOR</p><h1>${esc(a.name)}</h1><p>${esc(a.tagline||'')}</p>${tags(a.genres)}<dl class="amb-info"><dt>PROFILE</dt><dd>${esc(a.profile||a.introduction||'')}</dd><dt>AREA</dt><dd>${esc(a.area||'')}</dd><dt>対応可能な案件</dt><dd>${arr(a.services).map(esc).join(' / ')}</dd><dt>SNS</dt><dd class="amb-tags">${social||'掲載準備中'}</dd><dt>NOX RECOMMEND</dt><dd>${esc(a.recommendation||'NOXが案件内容を確認し、最適な形をご提案します。')}</dd><dt>料金</dt><dd>${a.priceVisible?esc(a.priceSummary||'要相談'):'料金は案件内容・ご希望のアンバサダー・PR方法に応じて個別にご案内いたします。'}</dd></dl><div class="amb-note">案件受付・条件調整・契約・料金・進行は、すべてNOXが窓口となります。</div><div class="amb-cta-stack"><a class="amb-btn gold" href="ambassador-inquiry.html?ambassador=${encodeURIComponent(a.name)}">このアンバサダーを希望してPR相談</a><a class="amb-btn" href="ambassador-inquiry.html?ambassador=NOXにおまかせ">NOXにおまかせで相談する</a></div></article>`;setupViewer(urls)}
async function inquiryPage(){const form=document.querySelector('#inquiryForm');if(!form)return;const select=form.elements.ambassador;const requested=new URLSearchParams(location.search).get('ambassador')||'NOXにおまかせ';let sent=false;try{const rows=await loadPublic();rows.forEach(a=>select.add(new Option(a.name,a.name)))}catch{}select.value=[...select.options].some(o=>o.value===requested)?requested:'NOXにおまかせ';form.addEventListener('submit',async e=>{e.preventDefault();if(sent)return;const status=document.querySelector('#formStatus');const submit=form.querySelector('[type=submit]');submit.disabled=true;status.textContent='送信しています…';const data=Object.fromEntries(new FormData(form));data.channels=new FormData(form).getAll('channels');data.status='new';data.createdAt=serverTimestamp();try{await addDoc(collection(db,'ambassadorInquiries'),data);sent=true;form.reset();select.value='NOXにおまかせ';submit.textContent='送信済み';status.textContent='ご相談を受け付けました。NOX担当者よりご連絡いたします。'}catch(err){status.textContent='送信できませんでした。入力内容をご確認のうえ、もう一度お試しください。';submit.disabled=false}})}
listPage();detailPage();inquiryPage();
