import { app, auth, db } from "./firebase-db.js";
import { requireActiveAdmin } from "./admin-authorization.js";
import { collection, deleteDoc, doc, getDocs, orderBy, query, serverTimestamp, setDoc, updateDoc } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";
import { deleteObject, getDownloadURL, getStorage, ref, uploadBytes } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-storage.js";
import { DONATION_STATUSES, MARKET_CATEGORIES, MARKET_CONDITIONS, escapeHtml, formatDate, safeImageUrl, yen } from "./market-data.js";
const user = await requireActiveAdmin({ auth, db, loginUrl: "./login.html?reason=admin-required" }); if (!user) throw new Error("admin required"); document.body.style.visibility = "visible";
const storage = getStorage(app), state = document.querySelector("[data-state]"), form = document.querySelector("[data-product-form]"); let products = [], donations = [];
const options = values => values.map(value => `<option>${escapeHtml(value)}</option>`).join(""); form.category.innerHTML = options(MARKET_CATEGORIES); form.condition.innerHTML = options(MARKET_CONDITIONS);
const setState = text => state.textContent = text;
document.querySelectorAll("[data-tab]").forEach(button => button.addEventListener("click", () => { document.querySelectorAll("[data-tab]").forEach(item => item.classList.toggle("secondary", item !== button)); document.querySelectorAll("[data-panel]").forEach(panel => panel.classList.toggle("hidden", panel.dataset.panel !== button.dataset.tab)); }));
function resetForm() { form.reset(); form.id.value = ""; form.stock.value = "1"; document.querySelector("[data-product-form-title]").textContent = "商品を追加"; }
document.querySelector("[data-cancel-edit]").addEventListener("click", resetForm);
async function uploadProductImages(id, files) { const images = []; for (const file of files) { if (!["image/jpeg", "image/png", "image/webp"].includes(file.type) || file.size > 8 * 1024 * 1024) throw new Error("画像はJPEG・PNG・WebP、各8MB以内にしてください。"); const extension = file.type.split("/")[1].replace("jpeg", "jpg"); const path = `market-products/${id}/${crypto.randomUUID()}.${extension}`; const result = await uploadBytes(ref(storage, path), file, { contentType: file.type }); images.push({ path, url: await getDownloadURL(result.ref) }); } return images; }
form.addEventListener("submit", async event => { event.preventDefault(); const id = form.id.value || doc(collection(db, "marketProducts")).id, old = products.find(item => item.id === id), files = [...form.images.files]; if ((old?.images?.length || 0) + files.length > 10) return alert("商品画像は最大10枚です。"); setState("保存中…"); try { const added = await uploadProductImages(id, files); await setDoc(doc(db, "marketProducts", id), { name: form.name.value.trim(), price: Number(form.price.value), category: form.category.value, brand: form.brand.value.trim(), condition: form.condition.value, stock: Number(form.stock.value), size: form.size.value.trim(), color: form.color.value.trim(), description: form.description.value.trim(), caution: form.caution.value.trim(), isPublic: form.isPublic.checked, soldOut: form.soldOut.checked, images: [...(old?.images || []), ...added], createdAt: old?.createdAt || serverTimestamp(), updatedAt: serverTimestamp(), updatedBy: user.uid }, { merge: true }); resetForm(); await loadProducts(); setState("保存しました"); } catch (error) { console.error(error); setState("保存に失敗しました"); alert(error.message || "保存できませんでした。"); } });
function productMarkup(item) { const images = (item.images || []).filter(image => safeImageUrl(image.url)); return `<article class="admin-card"><div class="admin-card-head"><div><span class="status-pill">${item.isPublic ? "公開" : "非公開"} / ${item.soldOut ? "SOLD OUT" : `在庫 ${Number(item.stock)}`}</span><h3>${escapeHtml(item.name)}</h3><p>${escapeHtml(item.category)} / ${escapeHtml(item.condition)} / ${yen(item.price)}</p></div><div class="market-actions" style="margin:0"><button class="market-button secondary" data-edit="${item.id}">編集</button><button class="market-button secondary" data-toggle="${item.id}">${item.isPublic ? "非公開にする" : "公開する"}</button><button class="market-button secondary" data-sold="${item.id}">${item.soldOut ? "販売中に戻す" : "SOLD OUT"}</button><button class="market-button danger" data-delete="${item.id}">削除</button></div></div>${images.length ? `<div class="admin-images">${images.map((image, index) => `<span><img src="${escapeHtml(image.url)}" alt=""><button class="market-button danger" data-remove-image="${item.id}" data-index="${index}" type="button">画像削除</button></span>`).join("")}</div>` : ""}</article>`; }
async function loadProducts() { const snapshot = await getDocs(query(collection(db, "marketProducts"), orderBy("createdAt", "desc"))); products = snapshot.docs.map(item => ({ id: item.id, ...item.data() })); const root = document.querySelector("[data-products]"); root.innerHTML = products.length ? products.map(productMarkup).join("") : '<p class="market-empty">商品はまだありません。</p>'; bindProductActions(root); }
function bindProductActions(root) { root.querySelectorAll("[data-edit]").forEach(button => button.onclick = () => editProduct(button.dataset.edit)); root.querySelectorAll("[data-toggle]").forEach(button => button.onclick = async () => { const item = products.find(value => value.id === button.dataset.toggle); await updateDoc(doc(db, "marketProducts", item.id), { isPublic: !item.isPublic, updatedAt: serverTimestamp(), updatedBy: user.uid }); await loadProducts(); }); root.querySelectorAll("[data-sold]").forEach(button => button.onclick = async () => { const item = products.find(value => value.id === button.dataset.sold); await updateDoc(doc(db, "marketProducts", item.id), { soldOut: !item.soldOut, updatedAt: serverTimestamp(), updatedBy: user.uid }); await loadProducts(); }); root.querySelectorAll("[data-delete]").forEach(button => button.onclick = () => removeProduct(button.dataset.delete)); root.querySelectorAll("[data-remove-image]").forEach(button => button.onclick = () => removeImage(button.dataset.removeImage, Number(button.dataset.index))); }
function editProduct(id) { const item = products.find(value => value.id === id); for (const [key, value] of Object.entries(item)) if (form.elements[key]) form.elements[key].type === "checkbox" ? form.elements[key].checked = Boolean(value) : form.elements[key].value = value ?? ""; form.id.value = id; document.querySelector("[data-product-form-title]").textContent = "商品を編集"; scrollTo({ top: form.offsetTop - 80, behavior: "smooth" }); }
async function removeImage(id, index) { const item = products.find(value => value.id === id), image = item.images[index]; if (!confirm("この画像を削除しますか？")) return; await updateDoc(doc(db, "marketProducts", id), { images: item.images.filter((_, value) => value !== index), updatedAt: serverTimestamp(), updatedBy: user.uid }); if (image?.path) await deleteObject(ref(storage, image.path)).catch(console.error); await loadProducts(); }
async function removeProduct(id) { const item = products.find(value => value.id === id); if (!confirm(`「${item.name}」を完全に削除しますか？`)) return; await deleteDoc(doc(db, "marketProducts", id)); await Promise.all((item.images || []).map(image => image.path ? deleteObject(ref(storage, image.path)).catch(console.error) : null)); await loadProducts(); setState("商品を削除しました"); }
function donationMarkup(item) { return `<article class="admin-card"><div class="admin-card-head"><div><span class="status-pill">${escapeHtml(item.status)}</span><h3>${escapeHtml(item.productName)}</h3><p>受付日 ${formatDate(item.createdAt)} / 発送予定 ${escapeHtml(item.shippingDate)}</p><p>${escapeHtml(item.name)} / ${escapeHtml(item.email)} / ${escapeHtml(item.phone)}</p><p>${escapeHtml(item.category)} / ${escapeHtml(item.brand || "ブランドなし")} / ${escapeHtml(item.condition)}</p></div><label class="market-field">ステータス<select data-donation-status="${item.id}">${DONATION_STATUSES.map(status => `<option ${status === item.status ? "selected" : ""}>${status}</option>`).join("")}</select></label></div><p style="white-space:pre-wrap">${escapeHtml(item.description)}</p><div class="admin-images">${(item.images || []).map(image => safeImageUrl(image.url) ? `<a href="${escapeHtml(image.url)}" target="_blank" rel="noopener"><img src="${escapeHtml(image.url)}" alt="商品画像"></a>` : "").join("")}</div><details><summary>同意記録を確認</summary><p>同意バージョン ${Number(item.agreementVersion || 0)} / 6項目すべて同意: ${Object.values(item.agreements || {}).filter(Boolean).length === 6 ? "はい" : "要確認"}</p></details></article>`; }
async function loadDonations() { const snapshot = await getDocs(query(collection(db, "marketDonations"), orderBy("createdAt", "desc"))); donations = await Promise.all(snapshot.docs.map(async item => { const data = { id: item.id, ...item.data() }; data.images = await Promise.all((data.images || []).map(async image => image.url ? image : { ...image, url: image.path ? await getDownloadURL(ref(storage, image.path)).catch(() => "") : "" })); return data; })); const root = document.querySelector("[data-donations]"); root.innerHTML = donations.length ? donations.map(donationMarkup).join("") : '<p class="market-empty">提供申請はまだありません。</p>'; root.querySelectorAll("[data-donation-status]").forEach(select => select.onchange = async () => { await updateDoc(doc(db, "marketDonations", select.dataset.donationStatus), { status: select.value, updatedAt: serverTimestamp(), updatedBy: user.uid }); setState("申請ステータスを更新しました"); }); }
await Promise.all([loadProducts(), loadDonations()]); setState("最新の状態です");
