import { auth } from "./firebase.js";
import { getFunctions, httpsCallable } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-functions.js";
const functions=getFunctions(auth.app,"asia-northeast1"),getPage=httpsCallable(functions,"getPublicStoreCustomerPage"),submit=httpsCallable(functions,"submitStoreReservation"),track=httpsCallable(functions,"trackStoreCustomerEvent");
const params=new URLSearchParams(location.search),el=document.getElementById("content"),storeId=params.get("id")||"",jobId=/^[A-Za-z0-9_-]+$/.test(params.get("jobId")||"")?params.get("jobId")||"":"";
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const safe=v=>{try{const u=new URL(String(v||""));return ["https:","http:"].includes(u.protocol)?u.href:""}catch{return""}};
const eventId=()=>crypto.randomUUID?.()||`${Date.now()}_${Math.random()}`;const visitorId=localStorage.getItem('nox_store_visitor')||(()=>{const id=eventId();localStorage.setItem('nox_store_visitor',id);return id})();
async function fire(type){try{await track({storeId,eventType:type,eventId:eventId(),visitorId})}catch{}}
const reservationFormObserver=new MutationObserver(()=>{if(document.getElementById("reservationForm")){reservationFormObserver.disconnect();fire("reservation_form_view")}});reservationFormObserver.observe(el,{childList:true,subtree:true});
function info(label,value){return value?`<div class="store-info"><small>${esc(label)}</small><div>${esc(value)}</div></div>`:""}
function render(page,jobs){const cover=safe(page.coverImageUrl),main=safe(page.mainImageUrl),phone=String(page.phone||"").replace(/[^+0-9]/g,"");el.innerHTML=`
<header class="store-hero" style="${cover?`background-image:url('${esc(cover)}')`:""}"><div class="store-hero-copy"><span class="store-badge">お客様向け店舗情報</span><h1>${esc(page.storeName)}</h1><p>${esc(page.category)}</p></div></header>
<section class="store-section store-profile">${main?`<img class="store-profile-image" src="${esc(main)}" alt="${esc(page.storeName)} プロフィール画像">`:""}<div><h2>店舗について</h2><p>${esc(page.description).replace(/\n/g,"<br>")}</p><div class="store-grid">${info("住所",page.address)}${info("最寄り駅",page.station)}${info("営業時間",page.businessHours)}${info("定休日",page.closedDay)}</div></div></section>
${page.prices?.length?`<section class="store-section"><h2>料金</h2>${page.prices.map(p=>`<div class="price-row"><strong>${esc(p.label)}</strong><b>${esc(p.price)}</b><small>${esc(p.note)}</small></div>`).join("")}</section>`:""}
${page.benefitEnabled?`<section class="store-section"><span class="store-badge">NOX限定特典</span><h2>${esc(page.benefitTitle)}</h2><p>${esc(page.benefitContent)}</p><small>${esc(page.benefitConditions)} ${esc(page.benefitNotes)} ${page.benefitExpiresAt?`有効期限 ${esc(page.benefitExpiresAt)}`:""}</small></section>`:""}
${page.galleryImages?.length?`<section class="store-section"><h2>店舗画像</h2><div class="store-gallery">${page.galleryImages.map(url=>`<img src="${esc(safe(url))}" alt="${esc(page.storeName)} 店舗画像" loading="lazy">`).join("")}</div></section>`:""}
<section class="store-section"><h2>予約・お問い合わせ</h2><div class="store-actions">${page.lineReservationEnabled&&safe(page.lineUrl)?`<a class="store-button" data-track="line_click" href="${esc(safe(page.lineUrl))}" target="_blank" rel="noopener">LINEで予約</a>`:""}${page.instagramReservationEnabled&&safe(page.instagramUrl)?`<a class="store-button" data-track="external_click" href="${esc(safe(page.instagramUrl))}" target="_blank" rel="noopener">Instagram DM</a>`:""}${page.xReservationEnabled&&safe(page.xUrl)?`<a class="store-button" data-track="external_click" href="${esc(safe(page.xUrl))}" target="_blank" rel="noopener">X DM</a>`:""}${page.tiktokReservationEnabled&&safe(page.tiktokUrl)?`<a class="store-button" data-track="external_click" href="${esc(safe(page.tiktokUrl))}" target="_blank" rel="noopener">TikTok</a>`:""}${page.phoneReservationEnabled&&phone?`<a class="store-button" data-track="phone_click" href="tel:${esc(phone)}">電話で予約</a>`:""}${page.externalReservationEnabled&&safe(page.externalReservationUrl)?`<a class="store-button" data-track="external_click" href="${esc(safe(page.externalReservationUrl))}" target="_blank" rel="noopener">${esc(page.externalReservationLabel||'予約サイトへ')}</a>`:""}</div>
${page.reservationFormEnabled?`<form id="reservationForm" class="store-form"><label>お名前<input name="name" maxlength="100" required></label><label>電話番号<input name="phone" type="tel" required></label><label>希望日<input name="desiredDate" type="date" required></label><label>希望時間<input name="desiredTime" type="time" required></label><label>人数<input name="people" type="number" min="1" max="30" value="1" required></label><label class="full">ご希望内容<textarea name="content" maxlength="1000"></textarea></label><label class="full">備考<textarea name="notes" maxlength="1000"></textarea></label><input name="website" tabindex="-1" autocomplete="off" hidden><button class="store-button full" type="submit">予約を送信</button><p id="formStatus" class="full" role="status"></p></form>`:""}</section>
${jobs?.length?`<section class="store-section"><h2>このお店で働く</h2>${jobs.map(j=>`<a class="store-button secondary" href="./job-detail.html?id=${encodeURIComponent(j.jobId)}">${esc(j.title)}</a>`).join(" ")}</section>`:""}`;
document.querySelectorAll("[data-track]").forEach(a=>a.addEventListener("click",()=>fire(a.dataset.track)));const form=document.getElementById("reservationForm");if(form)form.addEventListener("submit",async e=>{e.preventDefault();const button=form.querySelector("button"),status=document.getElementById("formStatus"),key=`nox_res_${storeId}`;button.disabled=true;status.textContent="送信中…";fire("reservation_click");try{const data=Object.fromEntries(new FormData(form));await submit({...data,storeId,jobId,people:Number(data.people),requestId:sessionStorage.getItem(key)||(()=>{const id=eventId();sessionStorage.setItem(key,id);return id})()});sessionStorage.removeItem(key);status.textContent="予約リクエストを送信しました。店舗またはNOX運営からの確認連絡をお待ちください。";form.reset()}catch(error){const code=String(error?.code||"");status.textContent=code.includes("already-exists")?"同じ予約リクエストはすでに送信されています。":code.includes("invalid-argument")?"入力内容に問題があります。各項目をご確認ください。":code.includes("failed-precondition")||code.includes("not-found")?"現在この店舗ではNOX予約を受け付けていません。":code.includes("unavailable")||code.includes("network-request-failed")?"通信に失敗しました。通信環境をご確認ください。":"サーバー側で一時的な問題が発生しています。時間をおいて再度お試しください。"}finally{button.disabled=false}});if(form&&location.hash==="#reservationForm")requestAnimationFrame(()=>form.scrollIntoView({behavior:"smooth",block:"start"}));fire("page_view")}
getPage({storeId}).then(r=>render(r.data.page,r.data.jobs)).catch(()=>{el.innerHTML='<section class="store-section"><h1>店舗ページは公開されていません</h1><a class="gold-link" href="./jobs.html">求人一覧へ戻る</a></section>'});
